import React from "react";
import "../styles/GenReports.css";

const ReportModal = ({ onClose }) => {
  const currentDate = new Date().toLocaleDateString();
  const currentTime = new Date().toLocaleTimeString();

  return (
    <div className="modal-overlay">
      <div className="modal-content">
        <h2>QUICK REPORT</h2>
        <p className="datetime">
          Date: {currentDate} | Time: {currentTime}
        </p>

        <div className="report-summary">
          <h3>SUMMARY</h3>
          <p>Active Users: <span>15</span></p>
          <p>Total Books Borrowed: <span>5</span></p>
          <p>Total Books Returned: <span>0</span></p>
          <p>Total Overdue Books: <span>4</span></p>
        </div>

        <div className="report-footer">
          <p>Prepared by: <strong>ADMIN NAME</strong></p>
          <p>Generated by: LibReport System</p>
        </div>

        <button className="close-btn" onClick={onClose}>
          Close
        </button>
      </div>
    </div>
  );
};

export default ReportModal;
