import React, { useEffect, useState } from "react";
import "../styles/GenReports.css";
import api from "../api";

const GenReport = ({ onClose }) => {
  const currentDate = new Date().toLocaleDateString();
  const currentTime = new Date().toLocaleTimeString();
  const [counts, setCounts] = useState({ users: 0, books: 0, activeLoans: 0, visitsToday: 0 });

  useEffect(() => {
    api.get('/dashboard').then(r => setCounts(r.data.counts)).catch(()=>{});
  }, []);

  return (
    <div className="modal-overlay">
      <div className="modal-content">
        <button className="close-btn" onClick={onClose}>
          &times;
        </button>

        <h2>QUICK REPORT</h2>
        <p className="datetime">
          Date: {currentDate} | Time: {currentTime}
        </p>

        <div className="report-summary">
          <h3>SUMMARY</h3>
          <p>Active Users: <span>{counts.users}</span></p>
          <p>Total Books Borrowed: <span>{counts.activeLoans}</span></p>
          <p>Total Books: <span>{counts.books}</span></p>
          <p>Visits Today: <span>{counts.visitsToday}</span></p>
        </div>

        <div className="report-footer">
          <p>
            Prepared by: <strong>ADMIN NAME</strong>
          </p>
          <p>Generated by: LibReport System</p>
        </div>
      </div>
    </div>
  );
};

export default GenReport;
